---
# this file is only for production
# art-bot looks for this in ~/.config/art-bot/settings.yaml by default

# channel where bot reports what is being asked and any errors
monitoring_channel: art-bot-monitoring

# files are relative to $HOME if not absolute.
# you'll need to look these up in vault and create the files locally.
slack_api_token_file: .config/art-bot/slack-api-token
slack_app_token_file: .config/art-bot/slack-app-token
